---
local:
  host: http://localhost:4000
  live_services:
    - service: facilities_management
      frameworks: 
        - RM6232
        - RM6378
    - service: legal_panel_for_government
      frameworks: 
        - RM6360
    - service: legal_services
      frameworks: 
        - RM6240
    - service: management_consultancy
      frameworks: 
        - RM6187
        - RM6309
    - service: supply_teachers
      frameworks: 
        - RM6238
sandbox:
  host: https://cmp.cmp-sandbox.crowncommercial.gov.uk
  live_services:
    - service: facilities_management
      frameworks: 
        - RM6232
        - RM6378
    - service: legal_panel_for_government
      frameworks: 
        - RM6360
    - service: legal_services
      frameworks: 
        - RM6240
    - service: management_consultancy
      frameworks: 
        - RM6187
        - RM6309
    - service: supply_teachers
      frameworks: 
        - RM6238
cmpdev:
  host: https://cmp.cmpdev.crowncommercial.gov.uk
  live_services:
    - service: facilities_management
      frameworks: 
        - RM6232
        - RM6378
    - service: legal_panel_for_government
      frameworks: 
        - RM6360
    - service: legal_services
      frameworks: 
        - RM6240
    - service: management_consultancy
      frameworks: 
        - RM6187
        - RM6309
    - service: supply_teachers
      frameworks: 
        - RM6238
preview:
  host: https://marketplace.preview.crowncommercial.gov.uk
  live_services:
    - service: facilities_management
      frameworks: 
        - RM6232
        - RM6378
    - service: legal_panel_for_government
      frameworks: 
        - RM6360
    - service: legal_services
      frameworks: 
        - RM6240
    - service: management_consultancy
      frameworks:
        - RM6309
    - service: supply_teachers
      frameworks: 
        - RM6238
production:
  host: https://marketplace.service.crowncommercial.gov.uk
  live_services:
    - service: facilities_management
      frameworks: 
        - RM6232
    - service: legal_services
      frameworks: 
        - RM6240
    - service: legal_panel_for_government
      frameworks: 
        - RM6360
    - service: management_consultancy
      frameworks: 
        - RM6309
    - service: supply_teachers
      frameworks: 
        - RM6238
